coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 1%
        only_pulls: true
    patch:
      default:
        target: 80%
        threshold: 1%
        only_pulls: true

component_management:
  individual_components:
    - component_id: api
      name: API
      paths:
        - api/**
        - apitest/**
    - component_id: irc
      name: IRC
      paths:
        - irc/**
    - component_id: pubsub
      name: PubSub
      paths:
        - pubsub/**

ignore:
  - .codegen/**

comment:
  layout: "header, diff, components"
  hide_comment_details: false
  require_changes: true
