version: 2.1

jobs:
  run-tests:
    docker:
      - image: golang:latest
    working_directory: /go/src/github.com/Adeithe/go-twitch
    steps:
      - checkout
      - run:
          name: Get dependencies
          command: |
            mkdir /tmp/artifacts
            mkdir /tmp/insights
            go mod download
            go get github.com/jstemmer/go-junit-report
      - run:
          name: Run Tests
          command: | 
            go test -v -coverprofile=coverage.out -timeout=30s ./... | tee test.out
      - run:
          name: Store test results
          when: always
          command: |
            go tool cover -html=coverage.out -o=/tmp/artifacts/coverage.html ; rm coverage.out
            cat test.out | go-junit-report > /tmp/insights/report.xml ; rm test.out
      - store_artifacts:
          path: /tmp/artifacts
      - store_test_results:
          path: /tmp/insights
  report-card:
    docker:
      - image: golang:latest
    working_directory: /go/src/github.com/Adeithe/go-twitch
    steps:
      - checkout
      - run:
          name: Install gometalinter
          command: |
            cd $GOPATH
            curl -L https://git.io/vp6lP | sh
            go get github.com/gojp/goreportcard/cmd/goreportcard-cli
      - run:
          name: Report Card
          command: |
            go mod download
            goreportcard-cli -v

workflows:
  build:
    jobs:
      - run-tests
      - report-card
