version: 2.1

jobs:
  run-tests:
    docker:
      - image: golang:latest
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run:
          name: Get dependencies
          command: |
            mkdir /tmp/artifacts
            mkdir /tmp/insights
            go get -v -t -d ./...
            go get github.com/tebeka/go2xunit
      - run:
          name: Run Tests
          command: | 
            go fmt ./... > /dev/null
            2>&1 go test -v -coverprofile=coverage.out -timeout=30s ./... | tee test.out
            go tool cover -html=coverage.out -o=/tmp/artifacts/coverage.html ; rm coverage.out
            go2xunit -fail -input test.out -output /tmp/insights/report.xml ; rm test.out
      - store_artifacts:
          path: /tmp/artifacts
      - store_test_results:
          path: /tmp/insights
  report-card:
    docker:
      - image: golang:latest
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run:
          name: Get dependencies
          command: |
            go get -v -t -d ./...
      - run:
          name: Install gometalinter
          command: |
            cd $GOPATH
            curl -L https://git.io/vp6lP | sh
            go get github.com/gojp/goreportcard/cmd/goreportcard-cli
      - run:
          name: Report Card
          command: |
            goreportcard-cli -v

workflows:
  build:
    jobs:
      - run-tests
      - report-card
